[workspace]
members = [
    "houtu",
    "houtu-app",
    "houtu-renderer",
    "houtu-scene",
    "houtu-jobs",
    "bevy_web_asset",
    "quantized-mesh-decoder",
]
resolver = "2"

[profile.release]
debug = true
