[workspace]
members = [
    "houtu-app",
    "houtu-renderer",
    "houtu-scene",
    "houtu-jobs",
    "bevy_web_asset",
]
resolver = "2"

[profile.release]
debug = true

[profile.dev.package."*"]
opt-level = 3