[package]
name = "houtu-scene"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "bevy_asset",
    "wayland",
    "png",
] }
geodesy = "0.9.2"
round = "0.1.2"

[dependencies.wgpu]
version = "0.14.0"
features = ["spirv"]