[package]
name = "houtu-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10.1", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
    "bevy_pbr",
    "png",
] }
houtu-scene = { path = "../houtu-scene" }
# bevy_atmosphere = "0.6.0"
# bevy-inspector-egui = "0.18.3"
